### PR TITLE
Numeric looking token fix

### LINKED ISSUE #55: Lef lexer issues with semi-numeric values
The LEF lexer currently doesn't like the following numeric looking values:
+ Floats with exponents, e.g: `EDGECAPACITANCE 40.567E-6 ;`
+ Strings with leading numbers, e.g.: `SITE 18T` 
    + ... Afaict the `18` is slurped as a number token and then there is a string token following

the referenced publicly available LEF:
https://github.com/idea-fasoc/OpenFASOC/blob/c11ceb17997648a975f99738a8890a2288143e08/openfasoc/common/platforms/sky130osu18Ths/lef/sky130_osu_sc_18T_hs.tlef

### PR DESCRIPTION
**Pull request by nanobowers**
Fixes #55 for numeric looking tokens.

I have some concerns over performance (relative to the previous implementation), as I constructed a `String` to capture relevant part of the chars iterator.  This can probably be improved, but it wasnt obvious to me that I had the right data to do it.  Also it is checking i32 || f64 conversion to str as a means of deciding.  It's possible a custom int/float lexer could shortcut by identifying the more trivial cases before resorting to the conversion routines.

Some tests were added with positive and integers, numeric floats and exponential floats, plus a token that starts with a number and has letters.

### CODE REVIEW

**Comment by dan-fritchman** [comment]
Awesome!

Re performance - I imagine you're presumably worried about the string allocations right?
  
The prevailing wisdom - particularly that used by `rustc` itself (as of last time I looked) - is something like: 
- Read the whole input into one big string at the beginning
- Never allocate again, just make references into that big input string

I'll check on whether that remains the case.  
Lef21's parser of course doesn't have that performance focus in general, at least not yet. We allocate all kinda stuff, e.g. the `String` layer-names in every pin and obstruction. We accordingly don't have great performance tracking or regressions (again, at least not yet). There are plenty of intermediate answers, such as pre-allocating a big bucket of strings and pulling from there.

File: lef21/src/read.rs [hunk 1]
```diff
@@ -201,12 +204,25 @@ impl<'src> LefLexer<'src> {
         let tok = self.emit(TokenType::WhiteSpace);
         Ok(Some(tok))
     }
-    /// Lex a number
-    fn lex_number(&mut self) -> LefResult<Option<Token>> {
-        while self.accept(|c| c.is_digit(10) || c == '.') {
+    /// Lex a number, but if not truly a number, return token with ttype [TokenType::Name]
+    fn lex_number(&mut self, leadchar: char) -> LefResult<Option<Token>> {
+        let mut nstring = String::new();
+        nstring.push(leadchar);
```
Comment (nanobowers) [inline lef21/src/read.rs:210]: The numeric conversion routines are what they are but I am still a bit annoyed by the need to allocate a new String, prepend the the peeked char and then tack on a str slice  from `self.chars.as_str()`.
For some reason that doesnt make sense to me the chars iterator is advanced one position so that I couldn't get just grab a simple slice of it (without missing the necessary first character).

**Comment by dan-fritchman** [comment]
@nanobowers - we ready to get some of your series of PRs merged? 

I think you had some more in mind - but we'd be happy to get the existing ones in.  
CC @rahulk29

**Comment by nanobowers** [comment]
@dan-fritchman I think they're still ready to go, so long as there's no merge conflicts.
